services:
  - docker

before_install:
  - docker image build -t tobycassidy/review_sentiment .


deploy:
  - docker login --username "$DOCKERUSER" --password "$DOCKERPWD"
  - docker image push tobycassidy/review_sentiment 
