language:
  - generic

services:
  - docker

before_install:
  - docker image build -t tobycassidy/review_sentiment .


before_deploy:
  - docker login --username "$DOCKERUSER" --password "$DOCKERPWD"
  

deploy:
  provider: script
  script: docker image push tobycassidy/review_sentiment 
  on:
    branch: main
